// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeaderMessage.proto

package com.italkmind.client.vo.protocol.body;

public final class HeaderMessage {
  private HeaderMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ItalkMindHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.italkmind.client.vo.protocol.body.ItalkMindHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 checkCode = 1;</code>
     */
    int getCheckCode();

    /**
     * <code>uint32 cmdType = 2;</code>
     */
    int getCmdType();

    /**
     * <code>uint64 messageId = 3;</code>
     */
    long getMessageId();
  }
  /**
   * Protobuf type {@code com.italkmind.client.vo.protocol.body.ItalkMindHeader}
   */
  public  static final class ItalkMindHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.italkmind.client.vo.protocol.body.ItalkMindHeader)
      ItalkMindHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ItalkMindHeader.newBuilder() to construct.
    private ItalkMindHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ItalkMindHeader() {
      checkCode_ = 0;
      cmdType_ = 0;
      messageId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ItalkMindHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              checkCode_ = input.readUInt32();
              break;
            }
            case 16: {

              cmdType_ = input.readUInt32();
              break;
            }
            case 24: {

              messageId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.italkmind.client.vo.protocol.body.HeaderMessage.internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.italkmind.client.vo.protocol.body.HeaderMessage.internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.class, com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.Builder.class);
    }

    public static final int CHECKCODE_FIELD_NUMBER = 1;
    private int checkCode_;
    /**
     * <code>uint32 checkCode = 1;</code>
     */
    public int getCheckCode() {
      return checkCode_;
    }

    public static final int CMDTYPE_FIELD_NUMBER = 2;
    private int cmdType_;
    /**
     * <code>uint32 cmdType = 2;</code>
     */
    public int getCmdType() {
      return cmdType_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 3;
    private long messageId_;
    /**
     * <code>uint64 messageId = 3;</code>
     */
    public long getMessageId() {
      return messageId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (checkCode_ != 0) {
        output.writeUInt32(1, checkCode_);
      }
      if (cmdType_ != 0) {
        output.writeUInt32(2, cmdType_);
      }
      if (messageId_ != 0L) {
        output.writeUInt64(3, messageId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (checkCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, checkCode_);
      }
      if (cmdType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, cmdType_);
      }
      if (messageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, messageId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader)) {
        return super.equals(obj);
      }
      com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader other = (com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader) obj;

      boolean result = true;
      result = result && (getCheckCode()
          == other.getCheckCode());
      result = result && (getCmdType()
          == other.getCmdType());
      result = result && (getMessageId()
          == other.getMessageId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CHECKCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCheckCode();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCmdType();
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.italkmind.client.vo.protocol.body.ItalkMindHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.italkmind.client.vo.protocol.body.ItalkMindHeader)
        com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.italkmind.client.vo.protocol.body.HeaderMessage.internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.italkmind.client.vo.protocol.body.HeaderMessage.internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.class, com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.Builder.class);
      }

      // Construct using com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        checkCode_ = 0;

        cmdType_ = 0;

        messageId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.italkmind.client.vo.protocol.body.HeaderMessage.internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_descriptor;
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader getDefaultInstanceForType() {
        return com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.getDefaultInstance();
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader build() {
        com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader buildPartial() {
        com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader result = new com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader(this);
        result.checkCode_ = checkCode_;
        result.cmdType_ = cmdType_;
        result.messageId_ = messageId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader) {
          return mergeFrom((com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader other) {
        if (other == com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader.getDefaultInstance()) return this;
        if (other.getCheckCode() != 0) {
          setCheckCode(other.getCheckCode());
        }
        if (other.getCmdType() != 0) {
          setCmdType(other.getCmdType());
        }
        if (other.getMessageId() != 0L) {
          setMessageId(other.getMessageId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int checkCode_ ;
      /**
       * <code>uint32 checkCode = 1;</code>
       */
      public int getCheckCode() {
        return checkCode_;
      }
      /**
       * <code>uint32 checkCode = 1;</code>
       */
      public Builder setCheckCode(int value) {
        
        checkCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 checkCode = 1;</code>
       */
      public Builder clearCheckCode() {
        
        checkCode_ = 0;
        onChanged();
        return this;
      }

      private int cmdType_ ;
      /**
       * <code>uint32 cmdType = 2;</code>
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>uint32 cmdType = 2;</code>
       */
      public Builder setCmdType(int value) {
        
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 cmdType = 2;</code>
       */
      public Builder clearCmdType() {
        
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private long messageId_ ;
      /**
       * <code>uint64 messageId = 3;</code>
       */
      public long getMessageId() {
        return messageId_;
      }
      /**
       * <code>uint64 messageId = 3;</code>
       */
      public Builder setMessageId(long value) {
        
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 messageId = 3;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.italkmind.client.vo.protocol.body.ItalkMindHeader)
    }

    // @@protoc_insertion_point(class_scope:com.italkmind.client.vo.protocol.body.ItalkMindHeader)
    private static final com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader();
    }

    public static com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ItalkMindHeader>
        PARSER = new com.google.protobuf.AbstractParser<ItalkMindHeader>() {
      @java.lang.Override
      public ItalkMindHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItalkMindHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ItalkMindHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ItalkMindHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.italkmind.client.vo.protocol.body.HeaderMessage.ItalkMindHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HeaderMessage.proto\022%com.italkmind.cli" +
      "ent.vo.protocol.body\"H\n\017ItalkMindHeader\022" +
      "\021\n\tcheckCode\030\001 \001(\r\022\017\n\007cmdType\030\002 \001(\r\022\021\n\tm" +
      "essageId\030\003 \001(\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_italkmind_client_vo_protocol_body_ItalkMindHeader_descriptor,
        new java.lang.String[] { "CheckCode", "CmdType", "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
