// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMessage.proto

package com.italkmind.client.vo.protocol.body;

public final class PushMessage {
  private PushMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAckMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.italkmind.client.vo.protocol.body.MsgAckMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 recType = 1;</code>
     */
    int getRecType();

    /**
     * <code>uint64 recId = 2;</code>
     */
    long getRecId();

    /**
     * <code>uint64 orderId = 3;</code>
     */
    long getOrderId();

    /**
     * <code>uint64 msgId = 4;</code>
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code com.italkmind.client.vo.protocol.body.MsgAckMessage}
   */
  public  static final class MsgAckMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.italkmind.client.vo.protocol.body.MsgAckMessage)
      MsgAckMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAckMessage.newBuilder() to construct.
    private MsgAckMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAckMessage() {
      recType_ = 0;
      recId_ = 0L;
      orderId_ = 0L;
      msgId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgAckMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              recType_ = input.readUInt32();
              break;
            }
            case 16: {

              recId_ = input.readUInt64();
              break;
            }
            case 24: {

              orderId_ = input.readUInt64();
              break;
            }
            case 32: {

              msgId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.class, com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.Builder.class);
    }

    public static final int RECTYPE_FIELD_NUMBER = 1;
    private int recType_;
    /**
     * <code>uint32 recType = 1;</code>
     */
    public int getRecType() {
      return recType_;
    }

    public static final int RECID_FIELD_NUMBER = 2;
    private long recId_;
    /**
     * <code>uint64 recId = 2;</code>
     */
    public long getRecId() {
      return recId_;
    }

    public static final int ORDERID_FIELD_NUMBER = 3;
    private long orderId_;
    /**
     * <code>uint64 orderId = 3;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private long msgId_;
    /**
     * <code>uint64 msgId = 4;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (recType_ != 0) {
        output.writeUInt32(1, recType_);
      }
      if (recId_ != 0L) {
        output.writeUInt64(2, recId_);
      }
      if (orderId_ != 0L) {
        output.writeUInt64(3, orderId_);
      }
      if (msgId_ != 0L) {
        output.writeUInt64(4, msgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (recType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, recType_);
      }
      if (recId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, recId_);
      }
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, orderId_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage)) {
        return super.equals(obj);
      }
      com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage other = (com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage) obj;

      boolean result = true;
      result = result && (getRecType()
          == other.getRecType());
      result = result && (getRecId()
          == other.getRecId());
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && (getMsgId()
          == other.getMsgId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RECTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRecType();
      hash = (37 * hash) + RECID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRecId());
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.italkmind.client.vo.protocol.body.MsgAckMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.italkmind.client.vo.protocol.body.MsgAckMessage)
        com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.class, com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.Builder.class);
      }

      // Construct using com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        recType_ = 0;

        recId_ = 0L;

        orderId_ = 0L;

        msgId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_descriptor;
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage getDefaultInstanceForType() {
        return com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage build() {
        com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage buildPartial() {
        com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage result = new com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage(this);
        result.recType_ = recType_;
        result.recId_ = recId_;
        result.orderId_ = orderId_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage) {
          return mergeFrom((com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage other) {
        if (other == com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage.getDefaultInstance()) return this;
        if (other.getRecType() != 0) {
          setRecType(other.getRecType());
        }
        if (other.getRecId() != 0L) {
          setRecId(other.getRecId());
        }
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int recType_ ;
      /**
       * <code>uint32 recType = 1;</code>
       */
      public int getRecType() {
        return recType_;
      }
      /**
       * <code>uint32 recType = 1;</code>
       */
      public Builder setRecType(int value) {
        
        recType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 recType = 1;</code>
       */
      public Builder clearRecType() {
        
        recType_ = 0;
        onChanged();
        return this;
      }

      private long recId_ ;
      /**
       * <code>uint64 recId = 2;</code>
       */
      public long getRecId() {
        return recId_;
      }
      /**
       * <code>uint64 recId = 2;</code>
       */
      public Builder setRecId(long value) {
        
        recId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 recId = 2;</code>
       */
      public Builder clearRecId() {
        
        recId_ = 0L;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <code>uint64 orderId = 3;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>uint64 orderId = 3;</code>
       */
      public Builder setOrderId(long value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 orderId = 3;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <code>uint64 msgId = 4;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>uint64 msgId = 4;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 msgId = 4;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.italkmind.client.vo.protocol.body.MsgAckMessage)
    }

    // @@protoc_insertion_point(class_scope:com.italkmind.client.vo.protocol.body.MsgAckMessage)
    private static final com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage();
    }

    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAckMessage>
        PARSER = new com.google.protobuf.AbstractParser<MsgAckMessage>() {
      @java.lang.Override
      public MsgAckMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgAckMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgAckMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAckMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.italkmind.client.vo.protocol.body.PushMessage.MsgAckMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgReqMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.italkmind.client.vo.protocol.body.MsgReqMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 sendId = 1;</code>
     */
    long getSendId();

    /**
     * <code>uint32 sendType = 2;</code>
     */
    int getSendType();

    /**
     * <code>uint64 orderId = 3;</code>
     */
    long getOrderId();

    /**
     * <code>uint64 msgId = 4;</code>
     */
    long getMsgId();
  }
  /**
   * Protobuf type {@code com.italkmind.client.vo.protocol.body.MsgReqMessage}
   */
  public  static final class MsgReqMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.italkmind.client.vo.protocol.body.MsgReqMessage)
      MsgReqMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgReqMessage.newBuilder() to construct.
    private MsgReqMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgReqMessage() {
      sendId_ = 0L;
      sendType_ = 0;
      orderId_ = 0L;
      msgId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgReqMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sendId_ = input.readUInt64();
              break;
            }
            case 16: {

              sendType_ = input.readUInt32();
              break;
            }
            case 24: {

              orderId_ = input.readUInt64();
              break;
            }
            case 32: {

              msgId_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.class, com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.Builder.class);
    }

    public static final int SENDID_FIELD_NUMBER = 1;
    private long sendId_;
    /**
     * <code>uint64 sendId = 1;</code>
     */
    public long getSendId() {
      return sendId_;
    }

    public static final int SENDTYPE_FIELD_NUMBER = 2;
    private int sendType_;
    /**
     * <code>uint32 sendType = 2;</code>
     */
    public int getSendType() {
      return sendType_;
    }

    public static final int ORDERID_FIELD_NUMBER = 3;
    private long orderId_;
    /**
     * <code>uint64 orderId = 3;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private long msgId_;
    /**
     * <code>uint64 msgId = 4;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sendId_ != 0L) {
        output.writeUInt64(1, sendId_);
      }
      if (sendType_ != 0) {
        output.writeUInt32(2, sendType_);
      }
      if (orderId_ != 0L) {
        output.writeUInt64(3, orderId_);
      }
      if (msgId_ != 0L) {
        output.writeUInt64(4, msgId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sendId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, sendId_);
      }
      if (sendType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sendType_);
      }
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, orderId_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, msgId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage)) {
        return super.equals(obj);
      }
      com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage other = (com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage) obj;

      boolean result = true;
      result = result && (getSendId()
          == other.getSendId());
      result = result && (getSendType()
          == other.getSendType());
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && (getMsgId()
          == other.getMsgId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SENDID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendId());
      hash = (37 * hash) + SENDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSendType();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.italkmind.client.vo.protocol.body.MsgReqMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.italkmind.client.vo.protocol.body.MsgReqMessage)
        com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.class, com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.Builder.class);
      }

      // Construct using com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sendId_ = 0L;

        sendType_ = 0;

        orderId_ = 0L;

        msgId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.italkmind.client.vo.protocol.body.PushMessage.internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_descriptor;
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage getDefaultInstanceForType() {
        return com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage build() {
        com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage buildPartial() {
        com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage result = new com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage(this);
        result.sendId_ = sendId_;
        result.sendType_ = sendType_;
        result.orderId_ = orderId_;
        result.msgId_ = msgId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage) {
          return mergeFrom((com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage other) {
        if (other == com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage.getDefaultInstance()) return this;
        if (other.getSendId() != 0L) {
          setSendId(other.getSendId());
        }
        if (other.getSendType() != 0) {
          setSendType(other.getSendType());
        }
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sendId_ ;
      /**
       * <code>uint64 sendId = 1;</code>
       */
      public long getSendId() {
        return sendId_;
      }
      /**
       * <code>uint64 sendId = 1;</code>
       */
      public Builder setSendId(long value) {
        
        sendId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 sendId = 1;</code>
       */
      public Builder clearSendId() {
        
        sendId_ = 0L;
        onChanged();
        return this;
      }

      private int sendType_ ;
      /**
       * <code>uint32 sendType = 2;</code>
       */
      public int getSendType() {
        return sendType_;
      }
      /**
       * <code>uint32 sendType = 2;</code>
       */
      public Builder setSendType(int value) {
        
        sendType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 sendType = 2;</code>
       */
      public Builder clearSendType() {
        
        sendType_ = 0;
        onChanged();
        return this;
      }

      private long orderId_ ;
      /**
       * <code>uint64 orderId = 3;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>uint64 orderId = 3;</code>
       */
      public Builder setOrderId(long value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 orderId = 3;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <code>uint64 msgId = 4;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <code>uint64 msgId = 4;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 msgId = 4;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.italkmind.client.vo.protocol.body.MsgReqMessage)
    }

    // @@protoc_insertion_point(class_scope:com.italkmind.client.vo.protocol.body.MsgReqMessage)
    private static final com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage();
    }

    public static com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgReqMessage>
        PARSER = new com.google.protobuf.AbstractParser<MsgReqMessage>() {
      @java.lang.Override
      public MsgReqMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgReqMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgReqMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgReqMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.italkmind.client.vo.protocol.body.PushMessage.MsgReqMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PushMessage.proto\022%com.italkmind.clien" +
      "t.vo.protocol.body\"O\n\rMsgAckMessage\022\017\n\007r" +
      "ecType\030\001 \001(\r\022\r\n\005recId\030\002 \001(\004\022\017\n\007orderId\030\003" +
      " \001(\004\022\r\n\005msgId\030\004 \001(\004\"Q\n\rMsgReqMessage\022\016\n\006" +
      "sendId\030\001 \001(\004\022\020\n\010sendType\030\002 \001(\r\022\017\n\007orderI" +
      "d\030\003 \001(\004\022\r\n\005msgId\030\004 \001(\004b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_italkmind_client_vo_protocol_body_MsgAckMessage_descriptor,
        new java.lang.String[] { "RecType", "RecId", "OrderId", "MsgId", });
    internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_italkmind_client_vo_protocol_body_MsgReqMessage_descriptor,
        new java.lang.String[] { "SendId", "SendType", "OrderId", "MsgId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
